### PR TITLE
Add functions to get appliance node High Availability and Health Status information

### LINKED ISSUE #157: Add appliance ha-nodes endpoint to sdk
Hello,
I really like this oneview package! I noticed the rest api reference has documentation about getting the appliance ha nodes information (via `/rest/appliance/ha-nodes`). This shows quite some information about appliances ha mode, which is useful in our scenario.
I am talking about [ha-nodes](https://techlibrary.hpe.com/docs/enterprise/servers/oneview5.0/cicf-api/en/index.html#rest/appliance/ha-nodes).
Can I submit a PR containing this info?
Regards,

### PR DESCRIPTION
**Pull request by trir262**
### Description
This change will add support to get the appliance node High Availability [HA Nodes](https://techlibrary.hpe.com/docs/enterprise/servers/oneview5.0/cicf-api/en/index.html#rest/appliance/ha-nodes) and appliance node [Health Status](https://techlibrary.hpe.com/docs/enterprise/servers/oneview5.0/cicf-api/en/index.html#rest/appliance/health-status) from the SDK

### Issues Resolved
Fixes #157 

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass for Python 2.7+ & 3.4+(`$ tox`).
- [X] New functionality has been documented in the README if applicable.
  - [X] New functionality has been thoroughly documented in the examples (please include helpful comments).
  - [X] New endpoints supported are updated in the endpoints-support.md file.
- [x] Changes are documented in the CHANGELOG file.

### CODE REVIEW

**Comment by trir262** [comment]
@VenkateshRavula @AsisBagga @nabhajit-ray or @yuvirani can somebody approve the workflow so I know if my PR passes the tests?

**Comment by VenkateshRavula** [comment]
Hi @trir262, Thanks for your contribution by raising this PR. But unfortunately this PR failed to pass the build validation tests because of some permission denied error.
Moreover the file which you tried to modify needs to be refactored before adding new changes. Also you have merged endpoints of different resources into single library file which is not accepted by our SDK team.
So we will be picking this as an enhancement request and make the necessary modifications to the library file to satisfy your requirement and will raise a different PR from our side. 
Soon we will get back to you with our fix.

**Comment by trir262** [comment]
Hello @VenkateshRavula 
What do you mean with 'the file I tried to modify needs to be refactored'? I did not see that anywhere in the repo?

Also I have no problem in splitting my resources in separate files. The reason why I merged it is because the specific rest endpoints refer to information about the same devices (appliances).

Just let me know if there's something you'd want me to do and I'll correct my PR

**Comment by VenkateshRavula** [comment]
> Hello @VenkateshRavula
> What do you mean with 'the file I tried to modify needs to be refactored'? I did not see that anywhere in the repo?
> 
> Also I have no problem in splitting my resources in separate files. The reason why I merged it is because the specific rest endpoints refer to information about the same devices (appliances).
> 
> Just let me know if there's something you'd want me to do and I'll correct my PR

There are few library files in our python repo which are using older base class "ResourceClient" and its methods. Then we have started refactoring our library files to use our new base class "Resource" and its methods. This is documented in our changelog as well. https://github.com/HewlettPackard/oneview-python/blob/master/CHANGELOG.md#500

So in our case "Appliance_node_information"(https://github.com/HewlettPackard/oneview-python/blob/master/hpeOneView/resources/settings/appliance_node_information.py) file is using older base class. So we have to refactor it to make us of new base class. Refer to "Firmware drivers"(https://github.com/HewlettPackard/oneview-python/blob/master/hpeOneView/resources/settings/firmware_drivers.py) for reference.

**Comment by VenkateshRavula** [comment]
Hi @trir262 , I have raised a separate PR with the required fix. Please find it below and also please close this PR.
https://github.com/HewlettPackard/oneview-python/pull/160

**Pull request closed without merging**
